project:
  type: website
  output-dir: docs

website:
  title: "Sophia Spisak"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
  page-footer: 
    background: light
    left: © Sophia Spisak 2026
    right: Made with {{< fa regular heart title="a heart" >}} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

