project:
  type: website
  output-dir: docs

website:
  title: "Sophia Spisak"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resources.qmd
  page-footer: # modified version of Sam Shanny-Csik's
    background: light
    left: © Sophia Spisak 2026
    right: Made with {{< fa regular heart title="a heart" >}} and [Quarto](https://quarto.org/docs/websites/){target=_blank}

format:
  html:
    theme: styles.scss
    mainfont: Figtree
    page-layout: full
    toc: true

editor: visual

